spring:
  datasource:
    url: jdbc:mysql://localhost:3306/khareedaari?useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update